language: java
env:
  global:
  - DISPLAY=:99
  - secure: "C2KikBx09qrE2dNiFVhOlhxkaAhpJX7lhQLKw1wWIP1K9QV1an/KHjA2MBk2+SoV2W0pp3alkxjNCXLYRDgyblUU0WPE+SCaK4picwVcVrlrymY3Jzko7u3fKFfmANoaaZAp2jnpQj6EIFnPO/aYMiCB/MrZF1P1tec2tZGuqeUInk+6pYlAh1LcfTBkvZLrqxLVfoPfP7Nvi7MGBSpAhN6nx4SGS0PAY8Wyw+9DdEwsS4eSt0ompGmbFvDgPa70gD853EkIInH2fAHDHYEch8Zy0Jm7Q9E8TFop3U7hijpaQfpVzuQ4VrydpVluTfueCxIh6lnjZNjQtlLkIBu46xrNQo2iQbNMPk1LRX3OPQqNWAz4QjLnrCdYJpHDZOVms97njH2RW8tG1LfoKVd40QgmC+5pFA8WUXBT7avIDH9RB7dp80oJJv47Jab5QunOBN077OT8Es7zKHLzFl5lde6YKpKsmIRrsJqjOJgM6FiKNcHi6wpxfoF1SNkcR+YZJl7HyyipfrXG94cjCluZLb1uyiCZGaZoqx4AsW0KJb8iBAEhgBDLKiLzvkm3JC/hOGdWzuQRI8vfHJVsFtc3d7lLSSaXGqiZjL0s/ivU/oRMNxBKRCXFsb4CbQG2SLhC7JJv3sTHegUFaCnSXOdPgupWgTdYNj+PE/FsudjkCkg="
  - # ^^ OSSRH_JIRA_USERNAME
  - secure: "WG6ET3RPl1fnFacdH9kYYHXe94rfmDrgKjddVuDsdAByzpAyRofN9PzKIOKOAPtQQGCLO06G60JG7yxEOAGNDU3kLPyrWAk0BAbJry2MDioBmIP5ae7KN7fUlHmikSGx0j+AoIziFp3WBKAQjCTzX95WfB3q0sHD4saear7skOR604ZsSddjtG36v+F7BJg2F6NnYY9mykuNLoznJFonF53xJn1VRQpkrSFd+5NKj4vBAvHTOyVR1gK0GlzglmgWJbpWqXNy5flhs8VdTOld5wg9WXCMIq1H8ua7D1aOQADI67FJMyIxNl7cAoK4rx+6KHY01qKOIfP9IMx0M7aWmkoVuGYWZ2BH3fWNZo8ZQBkLd7ULsBO3hqWF/gXHJdEOJhXrMXwGGIZdOyCNuwmwiHRLkVQkDKnenYtQsTVbpdb2nBfYDP+6wHy/aE3ysf0S6eJR8aqeprT2heIrE7YSaV8/1UkAh3ybIDB+fyCmon8TwEKBjG+Rbd0RGNlhJq4wi7G/yL58SXT0/qV1nwMCrwwUoqPY5eC+74ztx+EYmxsHWr1zgt8/XUZfGoSOZPESwIdpK+YV+SDdmQyuHHDlquamIQ1JOHLg179d4r5cxLbJ1qXjw02gr80AQ0vMKwPyVrE5KM1mIs4Cdf5WIv8mFi03qXMcDvBemjBywIQDvsA="
  - # ^^ OSSRH_JIRA_PASSWORD
  - secure: "j1foE09ntD6FfxPASa9WpgNAT1LxpBeXSq8+76lzF0q85mIxq7QrGMr/Wzlc/WXqe1svzt3n06avAZ2eVTqU/LMZYhqr/p+JweYHAsEo3ca0pmITAQe/QXU937LzCn71sPjLbT8zVqMkD0jvuh6SPAbqvWPdS7q9WT3E6MeJ95vxmW6z5tUKbnDwozh20Vba2/kcHuRUojnldfz3OdxCN1nQ/yhBnvMorMgzlO5IBRIPM0/8UjbIrg2mpTtn/KrJXRTjr7xmZ8yDb8I8PkLjzQZ8j7nDSm86stE8MUCa016nFtjKlnIaIDJa5qD+VTgDhVZZRkBT0vA8gVtQtNfhssxG7oFXNfvDW3WvPdR7RlpmM0sEBeYt/JGCxeKUKqKl5//+BA97YZ4YSqwMag4j9XPoCsgnDa4QkdE8DVWYA2On5JRUHdXWsSXI4I5Z25J5fl4wFzi11Ph48zMfTG0Bc6qYLpaxtX25rscQgP6b996Iox9pJHKF9DbAv54cGP7xQuyvL+fyYoqbpugGrPJypPIUTfusHWwnk/BuYL5mlKs4WKT1v1SYuam/Jft2QgSUqtKAbGSiwM1iHYJ3uO759Hsjyyuy75Bxr423Y/pDVAh1g7dmH3AUKYl+doyh2GhanxvVaczqnOQF5AgepHIYia/RJWCwZrLmtEALYXH0XW8="
  - # ^^ GPG_KEY_NAME
  - secure: "ntmgo5PPdQFriMuPR2gZMbisQLF0msuLTJKP83ezvUyS3BSC7gUS21fMhLvDxMmsfD3ohRojDFsGEokYG//fnAsSBisCqCUJ9n9/yfEaZHFDAKWKuiOb5YoqZoKMxgiEyOQoTg/Fi/EgFcwG0YVSa9c0Ze0Rj655qk0sxOczo/LVniPDvh9wZnWRXNxKYfDVFAwiVnqIpP/MgmEM8QPgNjX5ddhF/joODHhq/BNeT3we3HUT5G6UM5x3a4MEx4WvNxNqdGZY9JGT1ekKvqyA0IZV95YSDU8UqTdRbI/g7jOl5V4Akx+Rvcihiay1mEH8vBSeEfxk19uUGmRaSD7I+WAbYVu6/JT9zG+VpemaDEwO2tkmLxHftdkhUmgV+LgxEdsqwuHPMXSBA5/H0642gV8OZzdffLw4J63/ImXtaGlRsP2AGITh2iYYes38QENMFId45vEf+DsLDVy/V98nitmR94hwnCgwoJ9ggmtEgrr7g3tcm2plZaqqVytkasgXioTbhyEHwynxvDDVQR1LrkVdsusY+7/g85DRB+lgrbVXHY/5xp8/oszF4qDZZ6m2vC8xHkJUy0fT5VoE5phb6amEwwtcDGFUhKcU1M9wGyJ0hr9JR3T51dV5F6ap2cDils55zJld6JqGjxJa/FTcP6MHosIGlvyU6Yn2JR5NOco="
  - # ^^ GPG_PASSPHRASE
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B
jdk:
  - oraclejdk8
cache:
    directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
    - "$HOME/.gradle/"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then
      mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization="camel-tooling" -Dsonar.projectKey="camel-lsp-server" -Dsonar.projectName="Camel LSP Server";
      ./cd/before-deploy.sh;
      ./cd/deploy.sh; fi
deploy:
  provider: releases
  api_key: "${DEPLOY_TOKEN}"
  file: target/camel-lsp-server-1.0.0-SNAPSHOT.jar
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
addons:
  sonarcloud:
    organization: "camel-tooling"

