language: java
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
env:
  global:
  - GPG_DIR="`pwd`/cd"
branches:
  except:
    - /^dependabot.*$/
jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn verify -V
    - stage: test
      jdk: openjdk11
      script:
        - mvn verify -V
    - stage: test
      jdk: openjdk15
      script:
        - mvn verify -V
    - stage: deploy
      name: "Sonar Analysis and Deployment"
      jdk: openjdk11
      before_install: "export VERSION_SUFFIX=`grep '<version>' pom.xml -m 1 | cut -d'>' -f 2 | cut -d'<' -f 1 | cut -d'-' -f 2`"
      script:
        - if [[ $VERSION_SUFFIX == "SNAPSHOT" ]]; then
          export IS_SNAPSHOT=true;
         else
          export IS_SNAPSHOT=false;
         fi
        - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $IS_SNAPSHOT == "true" || -n "$TRAVIS_TAG" && $IS_SNAPSHOT == "false" ]]; then 
          mvn verify -P !build-extras -Dtest="*,!RunnerStandardIOTest,!RunnerWebSocketTest" -B sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization="camel-tooling" -Dsonar.projectKey="camel-lsp-server" -Dsonar.projectName="Camel LSP Server"; 
         fi
        - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $IS_SNAPSHOT == "true" ]]; then
         ./cd/before-deploy.sh;
         ./cd/deploy.sh;
         elif [[ -n "$TRAVIS_TAG" && $IS_SNAPSHOT == "false" ]]; then
         ./cd/before-deploy.sh;
         ./cd/deploy.sh;
         fi
      addons:
        sonarcloud:
          organization: camel-tooling
stages:
 - test
 - name: deploy
   if: branch = master AND NOT type = pull_request OR tag IS present
