matrix:
  include:
    - language: java
      sudo: false
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script:
        - 'mvn clean verify'
        - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN}; fi'
      jdk: oraclejdk8
      cache:
        directories:
          - $HOME/.m2
          - $HOME/.sonar/cache
          - $HOME/.gradle/
env: DISPLAY=:99
addons:
  sonarcloud:
    organization: "camel-tooling"
    branches:
      - master

