language: java
install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -P !build-extras -B
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
after_success:
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then mvn
  sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization="camel-tooling" -Dsonar.projectKey="camel-lsp-server" -Dsonar.projectName="Camel LSP Server"; 
  ./cd/before-deploy.sh;
  ./cd/deploy.sh; fi
deploy:
  provider: releases
  api_key: "${DEPLOY_TOKEN}"
  file: target/camel-lsp-server-1.0.0-SNAPSHOT.jar
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
addons:
  sonarcloud:
    organization: camel-tooling
