version: 2.1

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk11:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk15:
    docker:
      - image: circleci/openjdk:15-buster
    steps:
      - checkout
      - run: mvn verify -V

workflows:
  version: 2

  build:
    jobs:
      - jdk8
      - jdk11
      - jdk15
