version: 2.1

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk11:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk15:
    docker:
      - image: circleci/openjdk:15-buster
    steps:
      - checkout
      - run: mvn verify -V

  sonar:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: > 
          mvn verify
          -P !build-extras
          -Dtest="*,!RunnerStandardIOTest,!RunnerWebSocketTest"
          -B
          sonar:sonar
          -Dsonar.login=${SONAR_TOKEN}
          -Dsonar.organization="camel-tooling"
          -Dsonar.projectKey="camel-lsp-server"
          -Dsonar.projectName="Camel LSP Server"
          -Dsonar.host.url=https://sonarcloud.io

workflows:
  version: 2

  build:
    jobs:
      - jdk8
      - jdk11
      - jdk15
      - sonar:
          requires:
            - jdk8
            - jdk11
            - jdk15
          filters:
            branches:
              only:
                master
          context: sonarcloud
